# Generated by Django 5.2.14 on 2026-06-04 17:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_episode_item_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_local',
            field=models.ImageField(blank=True, help_text='Locally cached poster served from MEDIA_ROOT, if downloaded.', null=True, upload_to=app.models.poster_upload_path),
        ),
    ]
