# Generated by Django 5.2.14 on 2026-07-19 17:28

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_item_image_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Locally stored uploaded screenshot, if any.', upload_to=app.models.screenshot_upload_path)),
                ('url', models.URLField(blank=True, help_text='Hotlinked external screenshot URL, if any.', max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='app.item')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('image', ''), _negated=True), models.Q(('url', ''), _negated=True), _connector='OR'), name='screenshot_has_image_or_url')],
            },
        ),
    ]
