# Generated by Django 5.2.14 on 2026-05-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_customlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow anyone to view this list'),
        ),
    ]
