# Generated by Django 5.2.14 on 2026-05-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_user_jellyfin_mark_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Allow anyone to view your profile and lists'),
        ),
    ]
