# Generated by Django 5.2.14 on 2026-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anime_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='boardgame_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='book_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='comic_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='game_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='manga_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='movie_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='season_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tv_visibility',
            field=models.CharField(choices=[('everyone', 'Visible to everyone'), ('hidden_anon', 'Hidden from guests'), ('hidden_auth', 'Hidden from other users'), ('owner_only', 'Only me')], default='everyone', max_length=20),
        ),
    ]
